pub mod Errors {
    pub const THRESHOLD_TOO_SMALL: felt252 = 'THRESHOLD_TOO_SMALL';
    pub const L1_RECIPIENT_NOT_VERIFIED: felt252 = 'L1_RECIPIENT_NOT_VERIFIED';
    pub const LEGACY_TOKEN_BRIDGE_MISMATCH: felt252 = 'LEGACY_TOKEN_BRIDGE_MISMATCH';
    pub const REVERSE_SWAP_DISABLED: felt252 = 'REVERSE_SWAP_DISABLED';
    pub const INSUFFICIENT_CALLER_BALANCE: felt252 = 'INSUFFICIENT_CALLER_BALANCE';
    pub const INSUFFICIENT_ALLOWANCE: felt252 = 'INSUFFICIENT_ALLOWANCE';
    pub const INSUFFICIENT_CONTRACT_BALANCE: felt252 = 'INSUFFICIENT_CONTRACT_BALANCE';
    pub const TRANSFER_FAILED: felt252 = 'TRANSFER_FAILED';
}
