pub mod Errors {
    pub const CONTRACT_SETUP_NOT_FINALIZED: felt252 = 'CONTRACT_SETUP_NOT_FINALIZED';
    pub const L1_RECIPIENT_NOT_VERIFIED: felt252 = 'L1_RECIPIENT_NOT_VERIFIED';
    pub const LEGACY_TOKEN_BRIDGE_MISMATCH: felt252 = 'LEGACY_TOKEN_BRIDGE_MISMATCH';
    pub const REVERSE_SWAP_DISABLED: felt252 = 'REVERSE_SWAP_DISABLED';
    pub const INSUFFICIENT_CALLER_BALANCE: felt252 = 'INSUFFICIENT_CALLER_BALANCE';
    pub const INSUFFICIENT_CALLER_ALLOWANCE: felt252 = 'INSUFFICIENT_CALLER_ALLOWANCE';
    pub const INSUFFICIENT_SUPPLIER_BALANCE: felt252 = 'INSUFFICIENT_SUPPLIER_BALANCE';
    pub const INSUFFICIENT_SUPPLIER_ALLOWANCE: felt252 = 'INSUFFICIENT_SUPPLIER_ALLOWANCE';
    pub const INSUFFICIENT_LEGACY_ALLOWANCE: felt252 = 'INSUFFICIENT_LEGACY_ALLOWANCE';
    pub const TRANSFER_FROM_CALLER_FAILED: felt252 = 'TRANSFER_FROM_CALLER_FAILED';
    pub const TRANSFER_TO_CALLER_FAILED: felt252 = 'TRANSFER_TO_CALLER_FAILED';
    pub const TRANSFER_FROM_SUPPLIER_FAILED: felt252 = 'TRANSFER_FROM_SUPPLIER_FAILED';
    pub const SEND_TO_L1_FAILED: felt252 = 'SEND_TO_L1_FAILED';
    pub const INVALID_BATCH_SIZE: felt252 = 'INVALID_BATCH_SIZE';
}
