pub mod Errors {
    pub const THRESHOLD_TOO_SMALL: felt252 = 'THRESHOLD_TOO_SMALL';
    pub const L1_RECIPIENT_NOT_VERIFIED: felt252 = 'L1_RECIPIENT_NOT_VERIFIED';
    pub const LEGACY_TOKEN_BRIDGE_MISMATCH: felt252 = 'LEGACY_TOKEN_BRIDGE_MISMATCH';
    pub const SWAP_STATE_ALREADY_SET: felt252 = 'SWAP STATE ALREADY SET';
    pub const SWAP_DIRECTION_DISABLED: felt252 = 'SWAP DIRECTION DISABLED';
}
