[package]
name = "smart_contract_1"
readme = "README.md"
version.workspace = true
edition.workspace = true
license-file.workspace = true

[tool]
fmt.workspace = true
scarb.workspace = true

[dependencies]
starknet.workspace = true
openzeppelin.workspace = true
starkware_utils.workspace = true

[dev-dependencies]
assert_macros.workspace = true
snforge_std.workspace = true
openzeppelin_testing.workspace = true
starkware_utils_testing.workspace = true

[[test]]
name = "smart_contract_1_unittest"

[scripts]
test = "SNFORGE_BACKTRACE=1 snforge test"

[lib]

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true

[profile.dev.cairo]
unstable-add-statements-functions-debug-info = true
unstable-add-statements-code-locations-debug-info = true
inlining-strategy = "avoid"