name: Pull Request Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: foundry-rs/setup-snfoundry@v3
        with:
          starknet-foundry-version: "0.49.0"
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.12.2"

      - name: Install cairo-coverage
        run: |
          curl -L https://raw.githubusercontent.com/software-mansion/cairo-coverage/main/scripts/install.sh | sh

      - name: Run test
        run: scarb test -w

      # TODO: Add coverage once there's code.
      # - uses: codecov/codecov-action@v5.3.1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: packages/utils/coverage/coverage.lcov
      #     fail_ci_if_error: true

      - name: Check formatting
        run: |
          scarb fmt -w --check
